name: hexlet-cli-workflow  
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
	with:
	  node-version: '16'
      - run: make build
      - run: make lint
      - run: make test
